#!/usr/bin/env python3
"""Render the homepage, progress explorer, and player from matching.json.

The input is generated by scripts/generate_bazel_objdiff_report.py and already
contains original addresses/sizes, whole-binary objdiff scores, and Bazel
translation-unit ownership.
"""

from __future__ import annotations

import json
import math
import shutil
from pathlib import Path


def _all_functions(data):
    """Flatten unit-grouped, ambiguous, and unassigned function records."""
    functions = []
    for unit in data.get("units", []):
        for function in unit.get("functions", []):
            functions.append({**function, "unit": unit["name"], "ambiguous": False})
    for function in data.get("ambiguous_functions", []):
        functions.append({**function, "unit": None, "ambiguous": True})
    for function in data.get("unassigned_functions", []):
        functions.append({**function, "unit": None, "ambiguous": False})
    return sorted(functions, key=lambda item: (item["address"], item["name"]))


def build_unit_spans(text_start, text_size, functions):
    """Return address-ordered unit runs, including inter-function padding."""
    text_end = text_start + text_size
    ranges = []
    for function in functions:
        start = max(function["address"], text_start)
        end = min(function["address"] + function["size"], text_end)
        unit = None if function["ambiguous"] else function["unit"]
        if end > start:
            ranges.append((start, end, unit))

    clusters = []
    for start, end, unit in sorted(ranges):
        if clusters and start < clusters[-1][1]:
            cluster_start, cluster_end, owners = clusters[-1]
            clusters[-1] = (
                cluster_start,
                max(cluster_end, end),
                owners | ({unit} if unit is not None else set()),
            )
        else:
            clusters.append((start, end, {unit} if unit is not None else set()))

    spans = []
    current = None
    for start, end, owners in clusters:
        unit = next(iter(owners)) if len(owners) == 1 else None
        if current is not None and unit == current[0]:
            current = (current[0], current[1], max(current[2], end))
            continue
        if current is not None:
            spans.append((current[0], current[1], max(current[2], start)))
            current = None
        if unit is not None:
            current = (unit, start, end)
    if current is not None:
        spans.append(current)
    return spans


def build_payload(data, row_bytes, cell_bytes):
    """Convert the documented matching JSON into the compact browser payload."""
    text_start = data["text"]["address"]
    text_size = data["text"]["size"]
    text_end = text_start + text_size
    functions = _all_functions(data)
    unit_spans = build_unit_spans(text_start, text_size, functions)
    unit_names = sorted({function["unit"] for function in functions if function["unit"]})
    unit_ids = {name: index for index, name in enumerate(unit_names)}

    function_data = []
    for function in functions:
        start = max(function["address"], text_start)
        end = min(function["address"] + function["size"], text_end)
        if end <= start:
            continue
        function_data.append(
            {
                "a": start - text_start,
                "s": end - start,
                "n": function["demangled_name"],
                "r": function["name"],
                "u": unit_ids.get(function["unit"], -1),
                "p": function["match_percent"],
                "x": function["ambiguous"],
            }
        )

    span_data = [
        {"a": start - text_start, "s": end - start, "u": unit_ids[unit]}
        for unit, start, end in unit_spans
    ]
    return {
        "metrics": {
            "fuzzyMatchPercent": data["measures"]["fuzzy_match_percent"],
            "matchedFunctions": data["measures"]["matched_functions"],
            "totalFunctions": data["measures"]["total_functions"],
            "matchedCodePercent": data["measures"]["matched_code_percent"],
            "bazelUnits": data["summary"]["bazel_units"],
        },
        "sections": [
            {
                "n": section["name"],
                "a": section["address"],
                "s": section["size"],
                "k": section["kind"],
            }
            for section in data["sections"]
        ],
        "textStart": text_start,
        "textSize": text_size,
        "rowBytes": row_bytes,
        "cellBytes": cell_bytes,
        "rows": math.ceil(text_size / row_bytes),
        "units": unit_names,
        "functions": function_data,
        "spans": span_data,
    }


SITE_DIRECTORY = Path(__file__).resolve().parents[1] / "site"
SHARED_DIRECTORY = SITE_DIRECTORY / "shared"
HTML_TEMPLATE_PATH = SITE_DIRECTORY / "apps/progress/index.html"


COI_SERVICE_WORKER = r"""if (typeof window === "undefined") {
  self.addEventListener("install", () => self.skipWaiting());
  self.addEventListener("activate", event => event.waitUntil(self.clients.claim()));
  self.addEventListener("fetch", event => {
    // Only browsing contexts and workers need synthetic isolation headers.
    // Leave downloads to the browser so long OBB streams do not depend on
    // the service worker lifetime. Returning without respondWith bypasses it.
    if (!["document", "worker", "sharedworker"].includes(event.request.destination)) return;
    if (event.request.cache === "only-if-cached" && event.request.mode !== "same-origin") return;
    event.respondWith(fetch(event.request).then(response => {
      if (response.status === 0) return response;
      const headers = new Headers(response.headers);
      headers.set("Cross-Origin-Embedder-Policy", "require-corp");
      headers.set("Cross-Origin-Opener-Policy", "same-origin");
      headers.set("Cross-Origin-Resource-Policy", "same-origin");
      return new Response(response.body, {
        status: response.status,
        statusText: response.statusText,
        headers,
      });
    }));
  });
} else {
  window.sagaIsolationReady = new Promise((resolve, reject) => {
    const reloadKey = "saga-isolation-reload";
    if (window.crossOriginIsolated) {
      sessionStorage.removeItem(reloadKey);
      resolve();
      return;
    }
    if (!window.isSecureContext || !("serviceWorker" in navigator)) {
      reject(new Error("This build needs service workers and a secure browser window. Open the HTTPS site in a normal window; private browsing may disable service workers."));
      return;
    }
    let reloading = false;
    function reloadWhenControlled() {
      if (!navigator.serviceWorker.controller || reloading) return;
      try {
        if (sessionStorage.getItem(reloadKey)) {
          reject(new Error("Browser isolation setup failed after reloading. Allow service workers/site storage for this site, then reload in a normal browser window."));
          return;
        }
        reloading = true;
        sessionStorage.setItem(reloadKey, "1");
        location.reload();
      } catch (error) {
        reject(error);
      }
    }
    navigator.serviceWorker.addEventListener("controllerchange", reloadWhenControlled);
    navigator.serviceWorker.register("./coi-serviceworker.js").then(reloadWhenControlled, error => {
      reject(new Error(`Browser isolation setup failed: ${error.message}. Allow service workers/site storage for this site and reload.`));
    });
  });
  window.sagaIsolationReady.catch(() => {});
}
"""



def render_html(payload, template_path=HTML_TEMPLATE_PATH):
    encoded = json.dumps(payload, separators=(",", ":"), ensure_ascii=True)
    template = template_path.read_text(encoding="utf-8")
    return template.replace("/*__DATA__*/", encoded.replace("</", "<\\/"))


def render_header(root, current_page):
    header = (SHARED_DIRECTORY / "header.html").read_text(encoding="utf-8")
    for name in ("logo", "discord", "github"):
        icon = (SHARED_DIRECTORY / "assets" / f"{name}.svg").read_text(encoding="utf-8")
        if name != "logo":
            icon = icon.replace("<svg ", '<svg aria-hidden="true" ')
        header = header.replace(f"<!--__{name.upper()}__-->", icon)
    header = header.replace("__ROOT__", root)
    apps = json.loads((SITE_DIRECTORY / "apps.json").read_text())
    links = []
    for app in apps:
        current = ' aria-current="page"' if current_page == app["id"] else ""
        links.append(f'<a href="{root}{app["route"]}"{current}>{app["label"]}</a>')
    header = header.replace("<!--__NAVIGATION__-->", "\n".join(links))
    return header


def render_page(html, root, current_page):
    html = html.replace("<!--__HEADER__-->", render_header(root, current_page))
    for name, path in (
        ("HEAD", "head.html"),
        ("FOOTER", "footer.html"),
        ("LOGO", "assets/logo.svg"),
    ):
        html = html.replace(
            f"<!--__{name}__-->",
            (SHARED_DIRECTORY / path).read_text(encoding="utf-8"),
        )
    return html.replace("__ROOT__", root)


def generate_site(report_path, output_path, row_bytes, cell_bytes):
    with report_path.open(encoding="utf-8") as report_file:
        data = json.load(report_file)
    if data.get("schema_version") != 1:
        raise ValueError("unsupported or missing schema_version")
    payload = build_payload(data, row_bytes, cell_bytes)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    home = (SITE_DIRECTORY / "home.html").read_text(encoding="utf-8")
    home = home.replace(
        "__PROGRESS_PERCENT__", f"{payload['metrics']['fuzzyMatchPercent']:.2f}"
    )
    home = render_page(home, "./", "home")
    output_path.write_text(home, encoding="utf-8")
    progress_directory = output_path.parent / "progress"
    progress_directory.mkdir(exist_ok=True)
    progress = render_page(render_html(payload), "../", "progress")
    (progress_directory / "index.html").write_text(progress, encoding="utf-8")
    shutil.copyfile(
        SITE_DIRECTORY.parent / "build/site.css", output_path.parent / "site.css"
    )
    for name in ("favicon.svg", "favicon.png"):
        shutil.copyfile(SHARED_DIRECTORY / "assets" / name, output_path.parent / name)
    player_directory = output_path.parent / "play"
    player_directory.mkdir(exist_ok=True)
    player = (SITE_DIRECTORY / "apps/play/index.html").read_text(encoding="utf-8")
    player = render_page(player, "../", "play")
    (player_directory / "index.html").write_text(player, encoding="utf-8")
    with (player_directory / "coi-serviceworker.js").open(
        "w", encoding="utf-8"
    ) as service_worker_file:
        service_worker_file.write(COI_SERVICE_WORKER)
    apps = json.loads((SITE_DIRECTORY / "apps.json").read_text())
    for app in apps:
        if app["id"] in {"home", "play", "progress"}:
            continue
        directory = output_path.parent / app["route"]
        directory.mkdir(parents=True, exist_ok=True)
        content = (SITE_DIRECTORY / "apps" / app["id"] / "index.html").read_text()
        layout = (SHARED_DIRECTORY / "layout.html").read_text()
        layout = layout.replace("__WIDTH_CLASS__", "site-container-wide" if app.get("wide") else "")
        layout = layout.replace("__TITLE__", app["title"]).replace("<!--__CONTENT__-->", content)
        (directory / "index.html").write_text(render_page(layout, "../" * len(Path(app["route"]).parts), app["id"]), encoding="utf-8")
        for asset in (SITE_DIRECTORY / "apps" / app["id"]).glob("*.js"):
            shutil.copyfile(asset, directory / asset.name)
    (output_path.parent / ".nojekyll").touch()
    shutil.copyfile(SITE_DIRECTORY / "apps/nudat/example.dat", output_path.parent / "nudat/example.dat")
    return payload
